# ===============================================================================
# SleepyTime
# Author: mouseymars
# Website: http://taylorcraft.net
# ===============================================================================

# Percentage of players required to sleep for worlds to change time to day
playerAmount: 35

# Worlds for plugin to work in
worlds:
  - World
  - World_nether
  - World_the_end
  
#debug mode
debug: true