name: SleepyTime
version: 1.1.0
author: mouseymars
description: A simple plugin to configure server sleeping patterns
website: http://github.com/iaidan/sleepytime
main: net.aidantaylor.bukkit.sleepytime.SleepyTime
permissions:
   sleepytime.allow:
       description: Allows a user to be counted towards changing server time
       default: true